apiVersion: v1
kind: Service
metadata:
  labels:
    app: memos
  name: memos
spec:
  ports:
    - name: memos
      port: 5230
      targetPort: 5230
      protocol: TCP
      nodePort: 30230
  type: NodePort
  selector:
    app: memos
