apiVersion: v1
kind: Service
metadata:
  labels:
    app: alist
  name: alist
spec:
  ports:
    - name: alist
      port: 5244
      targetPort: 5244
      protocol: TCP
      nodePort: 30244
  type: NodePort
  selector:
    app: alist
